config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :user_currency_pairs
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency_pair_week_data.rb
class CurrencyPairWeekData < ApplicationRecord
  belongs_to :user_currency_pair

  scope :latest, -> { where(latest: true) }
  scope :highest, -> { where(boundry_type: 'highest') }
  scope :lowest, -> { where(boundry_type: 'lowest') }

  def highest?
    at_boundry? && boundry_type == 'highest'
  end

  def lowest?
    at_boundry? && boundry_type == 'lowest'
  end

  def special?
    latest? || at_boundry?
  end

  def at_boundry?
    boundry_type.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_currency_pairs
end

app/models/user_currency_pair.rb
class UserCurrencyPair < ApplicationRecord
  belongs_to :user
  has_many :currency_pair_week_datas

  validates :user, :base_currency, :target_currency, :amount, :weeks, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to user_currency_pairs_path
  end
end

app/controllers/user_currency_pairs_controller.rb
class UserCurrencyPairsController < ApplicationController
  before_action :load_user_currency_pair, only: %i[edit update destroy show]

  def new
    @user_currency_pair = UserCurrencyPair.new
  end

  def create
    @user_currency_pair = UserCurrencyPair.new(user_currency_pairs_params)
    if @user_currency_pair.save!
      LoadCurrencyPairDataJob.perform_later @user_currency_pair
      redirect_to user_currency_pairs_path, notice: 'successfully created'
    else
      render partial: :form, alert: 'Could not create'
    end
  end

  def index
    @user_currency_pairs = current_user.user_currency_pairs
  end

  def show
    @weekly_data =
      @user_currency_pair
      .currency_pair_week_datas.where(latest: nil)

    load_latest_rate
  end

  def edit; end

  def update
    if @user_currency_pair.update!(user_currency_pairs_params)
      LoadCurrencyPairDataJob.perform_later @user_currency_pair
      redirect_to user_currency_pairs_path, notice: 'successfully updated'
    else
      render :form, alert: 'Could not update'
    end
  end

  def destroy
    if @user_currency_pair.destroy
      redirect_to user_currency_pairs_path, notice: 'successfully deleted'
    else
      render :form, alert: 'Could not delete'
    end
  end

  private

  def user_currency_pairs_params
    @user_currency_pairs_params ||=
      params.require(:user_currency_pair)
            .permit(%i[user_id base_currency amount target_currency weeks])
  end

  def load_user_currency_pair
    @user_currency_pair = current_user.user_currency_pairs.find(params[:id])
    return if @user_currency_pair

    redirect_to user_currency_pairs_path, notice: 'Not Found'
  end

  def load_latest_rate
    latest_data = @user_currency_pair
                  .currency_pair_week_datas.find_by(week_start_date: Date.today)
    @latest_rate = latest_data&.rate
    return if @latest_rate

    response = FixerIoServices::ApiClient
               .new(@user_currency_pair.target_currency, false, Date.today)
               .call
    @latest_rate = JSON.parse(response.body)
                   .dig('rates', @user_currency_pair.target_currency).to_f
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_profit_loss(base_rate, rate)
    margin = rate - base_rate
    margin_percent = (margin.to_f / base_rate) * 100
    margin_percent.round(2)
  end

  def weekly_data_css_class(week_data)
    if week_data.highest?
      'table-success'
    elsif week_data.lowest?
      'table-warning'
    else
      ''
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arcanebet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'ArcaneBet', root_path, :class => 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              Logged in as <strong><%= current_user.email %></strong>.
            </li>
          <% end %>
        </ul>

        <ul class="navbar-nav my-2 my-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Settings
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link btn btn-primary'  %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link btn btn-info offset-sm-1'  %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <p><%= notice %></p>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <p><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/user_currency_pairs/_form.html.erb
<%= form_for @user_currency_pair, class: 'col-sm-10', url: user_currency_pairs_path, method: :post  do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :base_currency, value: 'EUR' %>
  <div class="form-group col-sm-4">
    <%= f.label :amount, 'Amount' %>
    <%= f.number_field :amount, class: "form-control", placeholder: 'Amount', required: true %>
  </div>
  <div class="form-group col-sm-4">
    <%= f.label :target_currency, 'Target Currency' %>
    <%=
      f.select :target_currency,
               options_for_select(Constants::SUPPORTED_CURRENCIES, selected: @user_currency_pair.target_currency),
               { prompt: 'Please  select a currency' },
               class: "form-control md-7", required: true
    %>
  </div>
  <div class="form-group col-sm-4">
    <%= f.label :weeks, 'Duration' %>
    <%= f.number_field :weeks, class: "form-control", placeholder: 'Duration(in weeks)', required: true %>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/user_currency_pairs/_user_currency_pairs.html.erb
<% @user_currency_pairs.each do |user_currency_pair| %>
  <tr>
    <th scope="row"><%= user_currency_pair.id %></th>
    <td><%= user_currency_pair.amount %></td>
    <td><%= user_currency_pair.base_currency %></td>
    <td><%= user_currency_pair.target_currency %></td>
    <td><%= user_currency_pair.weeks %></td>
    <td>
      <%= link_to 'Show', user_currency_pair_path(user_currency_pair), class: 'btn btn-success' %>
      <%= link_to 'Edit', edit_user_currency_pair_path(user_currency_pair), class: 'btn btn-info' %>
      <%= link_to 'Delete', user_currency_pair_path(user_currency_pair), method: :delete, class: 'btn btn-danger' %>
    </td>
  </tr>
<% end %>

app/views/user_currency_pairs/edit.html.erb
<%= render 'form' %>

app/views/user_currency_pairs/index.html.erb
<%= link_to 'New Currency Pair', new_user_currency_pair_path, class: 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Amount</th>
    <th scope="col">Base Currency</th>
    <th scope="col">Target Currency</th>
    <th scope="col">Weeks</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
    <%= render 'user_currency_pairs' %>
  </tbody>
</table>

app/views/user_currency_pairs/new.html.erb
<%= render 'form' %>

app/views/user_currency_pairs/show.html.erb
<div class="container col-sm-12">
  <div class="row">
    <div class="col-sm-8">
      <%= line_chart(
      @weekly_data.map{ |week_data| [week_data.week_start_date, week_data.rate.round(2)] },
      min: @weekly_data.find(&:lowest?).rate.round(2) - 1,
      max: @weekly_data.find(&:highest?).rate.round(2) + 1
      )
      %>
    </div>
    <div class="col-sm-2">
      <div class="card">
        <div class="card-header">
          Currency Pair Details
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Latest Price <%= @latest_rate.round(2) %></li>
          <li class="list-group-item">Base Currency: <%= @user_currency_pair.base_currency %></li>
          <li class="list-group-item">Target Currency: <%= @user_currency_pair.target_currency %></li>
          <li class="list-group-item">Amount: <%= @user_currency_pair.amount %></li>
          <li class="list-group-item">Weeks: <%= @user_currency_pair.weeks %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<br>
<br>

<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col">Year</th>
    <th scope="col">Week Number</th>
    <th scope="col">Week Start Date</th>
    <th scope="col">Rate</th>
    <th scope="col">Amount Valuation</th>
    <th scope="col">Profit/Loss</th>
  </tr>
  </thead>
  <tbody>
    <% @weekly_data.each do |weekly_data| %>
      <tr class="<%= weekly_data_css_class(weekly_data) %>">
        <th scope="row"><%= weekly_data.year %></th>
        <td><%= weekly_data.week_number %></td>
        <td><%= weekly_data.week_start_date %></td>
        <td><%= weekly_data.rate.round(2) %></td>
        <td><%= weekly_data.amount_valuation.round(2) %></td>
        <td><%= get_profit_loss(@latest_rate, weekly_data.rate) %></td>
      </tr>
    <% end %>
  </tbody>
</table>